# 과제1과 과제 2 모두 수행 후, 실행결과를 포함한 ipynb 파일을 제출할 것

# <과제1> 기본 코드 실습
- 와인 품질 데이터 : 와인 성분 변수들을 이용하여 품질을 예측하는 유명한 데이터

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import warnings
warnings.filterwarnings(action='ignore')

#### 데이터 불러오기 및 앞부분 확인

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [7]:
data = pd.read_csv('/content/gdrive/MyDrive/ybigta/wine.csv') #wine.csv도 '내드라이브'에 사본 저장 후, 경로 수정
data.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [8]:
#'인덱스 컬럼 드랍하기
data.drop("index",axis=1,inplace=True)
data.head()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

#### 데이터 shape 확인

In [10]:
data.shape

(5497, 13)

#### 컬럼명 확인

In [11]:
data.columns

Index(['quality', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'type'],
      dtype='object')

#### NaN, 데이터 타입, 개수 확인

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5497 entries, 0 to 5496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   quality               5497 non-null   int64
 1   fixed acidity         5497 non-null   float64
 2   volatile acidity      5497 non-null   float64
 3   citric acid           5497 non-null   float64
 4   residual sugar        5497 non-null   float64
 5   chlorides             5497 non-null   float64
 6   free sulfur dioxide   5497 non-null   float64
 7   total sulfur dioxide  5497 non-null   float64
 8   density               5497 non-null   float64
 9   pH                    5497 non-null   float64
 10  sulphates             5497 non-null   float64
 11  alcohol               5497 non-null   float64
 12  type                  5497 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 558.4+ KB

#### 통계값 확인

In [13]:
data.describe()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000
mean,5.818992,7.210115,0.338163,0.318543,5.438075,0.055808,30.417682,115.566491,0.994673,3.219502,0.530524,10.504918
std,0.870311,1.287579,0.163224,0.145104,4.756676,0.034653,17.673881,56.288223,0.003014,0.160713,0.149396,1.194524
min,3.000000,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.740000,0.220000,8.000000
25%,5.000000,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,78.000000,0.992300,3.110000,0.430000,9.500000
50%,6.000000,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994800,3.210000,0.510000,10.300000
75%,6.000000,7.700000,0.400000,0.390000,8.100000,0.064000,41.000000,155.000000,0.996930,3.320000,0.600000,11.300000
max,9.000000,15.900000,1.580000,1.660000,65.800000,0.610000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000

#### quality의 unique 확인

In [18]:
data.quality.unique()

array([5, 6, 7, 8, 4, 3, 9])

#### quality별로 개수 확인

In [19]:
data.quality.value_counts()

6    2416
5    1788
7     924
4     186
8     152
3      26
9       5
Name: quality, dtype: int64

#### 다음 컬럼만 따로 데이터프레임으로 추출해라 : 'quality', 'residual sugar', 'pH', 'alcohol', 'type'

In [14]:
condition = [ 'quality', 'residual sugar', 'pH', 'alcohol', 'type']
df = data[condition]
df.head()

   quality  residual sugar    pH  alcohol   type
0        5             6.8  3.44     10.2  white
1        5             2.4  3.19      9.5    red
2        5             2.0  3.05     10.9  white
3        6             6.0  3.26     10.8  white
4        6             9.5  3.04     10.9  white

#### groupby를 통해 quality로 묶고 통계값(min,mean,max) 확인

In [15]:
#min
df.groupby('quality').min()

         residual sugar    pH  alcohol   type
quality
3                  1.15  2.87      8.0    red
4                  0.70  2.74      8.6    red
5                  0.60  2.79      8.0    red
6                  0.70  2.74      8.4    red
7                  0.90  2.84      8.6    red
8                  0.80  2.94      8.8    red
9                  1.60  3.20     10.4  white

In [16]:
#mean
df.groupby('quality').mean()

         residual sugar        pH    alcohol
quality
3              5.203846  3.250385  10.251923
4              4.145430  3.228602  10.180376
5              5.792422  3.213384   9.846875
6              5.535141  3.219611  10.606015
7              4.748918  3.228333  11.383864
8              5.581579  3.216711  11.680921
9              4.120000  3.308000  12.180000

In [17]:
#max
df.groupby('quality').max()

         residual sugar    pH  alcohol   type
quality
3                 16.20  3.63     12.6  white
4                 15.40  3.90     13.5  white
5                 23.50  3.79     14.9  white
6                 65.80  4.01     14.0  white
7                 19.25  3.82     14.2  white
8                 14.80  3.57     14.0  white
9                 10.60  3.41     12.9  white

#### 알코올 함량을 기준으로 오름차순 정리  / 상위 30개만 출력

In [22]:
df.sort_values('alcohol',ascending='True').head(30)

      quality  residual sugar    pH  alcohol   type
4254        3            5.10  3.42      8.0  white
5077        5            0.95  3.34      8.0  white
1768        3            2.10  3.16      8.4    red
4176        5            3.30  3.16      8.4  white
479         6            1.80  2.86      8.4    red
3725        5           20.15  3.01      8.5  white
3772        6           18.00  2.98      8.5  white
172         6           18.00  2.98      8.5  white
255         5            1.60  3.15      8.5    red
3062        5            9.10  3.37      8.5  white
2377        5            1.30  3.19      8.5  white
1427        6            5.90  3.47      8.5  white
4249        4           10.80  3.08      8.6  white
3155        4            4.20  3.25      8.6  white
4224        6            4.90  3.03      8.6  white
3046        5           10.20  3.06      8.6  white
3640        7           14.60  3.21      8.6  white
30          5           16.00  3.13      8.6  white
3656        5           23.50  2.98      8.6  white
3355        4           13.30  3.06      8.6  white
5043        5           10.20  3.06      8.6  white
373         5           11.10  3.06      8.6  white
2111        5           13.10  3.39      8.6  white
55          7           14.60  3.21      8.6  white
5066        5           12.00  3.16      8.6  white
5302        6           13.30  3.03      8.6  white
686         5           15.00  2.93      8.6  white
4615        5           17.95  3.21      8.6  white
5353        4           10.80  3.08      8.6  white
4869        5           11.10  3.06      8.6  white

#### quailty가 7 이상인 데이터 추출 (20개)

In [24]:
df[df['quality']>=7].head(20)

     quality  residual sugar    pH  alcohol   type
11         7            1.10  3.32     10.9  white
12         7            6.85  3.03     11.9  white
17         7            4.80  3.17     12.2  white
25         8            3.90  3.24     12.6  white
45         7            1.40  3.22     11.5  white
46         7           12.80  3.14      9.1  white
53         7            1.80  3.08     13.7  white
54         8            6.10  3.08     12.5  white
55         7           14.60  3.21      8.6  white
60         7            3.60  3.31     13.1  white
63         7            2.10  3.26     12.4    red
71         8            7.05  3.25     11.1  white
74         7            1.10  3.61     10.3  white
79         7            1.10  3.48     11.0  white
87         7            4.50  3.45     12.6  white
89         7            1.80  3.05     11.8  white
101        7            2.90  3.17     11.0  white
104        7           10.40  3.04     11.5  white
119        7            2.90  3.02      9.5  white
120        7            6.30  3.54     11.6  white

#### 'strength' 컬럼추가 : alcohol을 기준으로 10도가 넘으면 'strong' 아니면 'weak'으로 표시 (상위 30개만 출력)

In [25]:
df['strength'] = df['alcohol'].apply(lambda x : 'strong' if x>10 else 'weak')
df.head(30)

    quality  residual sugar    pH  alcohol   type strength
0         5            6.80  3.44    10.20  white   strong
1         5            2.40  3.19     9.50    red     weak
2         5            2.00  3.05    10.90  white   strong
3         6            6.00  3.26    10.80  white   strong
4         6            9.50  3.04    10.90  white   strong
5         6            9.70  3.08    12.00  white   strong
6         5            1.50  3.30     9.60  white     weak
7         6           11.80  3.04    10.00  white     weak
8         5           18.30  3.30     8.70  white     weak
9         5           11.60  3.07     9.30  white     weak
10        6            0.90  2.89    12.70    red   strong
11        7            1.10  3.32    10.90  white   strong
12        7            6.85  3.03    11.90  white   strong
13        5            1.00  3.13     9.60  white     weak
14        5            2.60  3.10    10.50    red   strong
15        5            7.00  3.21    10.00  white     weak
16        5            2.10  3.04     9.30    red     weak
17        7            4.80  3.17    12.20  white   strong
18        6            7.50  3.06     9.70  white     weak
19        6           10.50  3.36    10.55  white   strong
20        5            1.70  3.10     9.80  white     weak
21        5            2.00  3.26     9.90    red     weak
22        6            1.20  3.11    11.20  white   strong
23        6            2.10  3.41    11.80    red   strong
24        5            2.50  3.34    10.50    red   strong
25        8            3.90  3.24    12.60  white   strong
26        5            2.20  3.30    10.20  white   strong
27        5           15.00  3.15     9.00  white     weak
28        6            1.60  3.27    10.80  white   strong
29        4            1.60  3.15    10.40  white   strong

#### merge 실습을 위한 데이터 쪼개기

In [26]:
df_x = data[['quality', 'fixed acidity', 'citric acid']].head(30)

In [27]:
df_y = data[['quality', 'volatile acidity', 'chlorides', 'alcohol']].head(30)

In [28]:
df_y = df_y[df_y.quality >= 7]

In [29]:
len(df_y)

4

#### df_x와 df_y를 inner join시켜라 (quality를 기준으로)

In [30]:
pd.merge(df_x, df_y, how='inner', on='quality')

   quality  fixed acidity  citric acid  volatile acidity  chlorides  alcohol
0        7            6.2         0.33              0.16      0.057     10.9
1        7            6.2         0.33              0.33      0.038     11.9
2        7            6.2         0.33              0.28      0.029     12.2
3        7            7.3         0.40              0.16      0.057     10.9
4        7            7.3         0.40              0.33      0.038     11.9
5        7            7.3         0.40              0.28      0.029     12.2
6        7            6.5         0.25              0.16      0.057     10.9
7        7            6.5         0.25              0.33      0.038     11.9
8        7            6.5         0.25              0.28      0.029     12.2
9        8            6.6         0.31              0.29      0.027     12.6

#### df_x에서 df_y를 left join시켜라 (quality를 기준으로)

In [31]:
pd.merge(df_x, df_y, how='left', on='quality')

    quality  fixed acidity  citric acid  volatile acidity  chlorides  alcohol
0         5            5.6         0.06               NaN        NaN      NaN
1         5            8.8         0.14               NaN        NaN      NaN
2         5            7.9         0.39               NaN        NaN      NaN
3         6            7.0         0.31               NaN        NaN      NaN
4         6            7.8         0.26               NaN        NaN      NaN
5         6            6.0         0.37               NaN        NaN      NaN
6         5            6.1         0.49               NaN        NaN      NaN
7         6            7.1         0.42               NaN        NaN      NaN
8         5            6.8         0.31               NaN        NaN      NaN
9         5            6.8         0.35               NaN        NaN      NaN
10        6            8.0         0.37               NaN        NaN      NaN
11        7            6.2         0.33              0.16      0.057     10.9
12        7            6.2         0.33              0.33      0.038     11.9
13        7            6.2         0.33              0.28      0.029     12.2
14        7            7.3         0.40              0.16      0.057     10.9
15        7            7.3         0.40              0.33      0.038     11.9
16        7            7.3         0.40              0.28      0.029     12.2
17        5            7.1         0.17               NaN        NaN      NaN
18        5           12.5         0.60               NaN        NaN      NaN
19        5            7.8         0.49               NaN        NaN      NaN
20        5            8.8         0.48               NaN        NaN      NaN
21        7            6.5         0.25              0.16      0.057     10.9
22        7            6.5         0.25              0.33      0.038     11.9
23        7            6.5         0.25              0.28      0.029     12.2
24        6            8.2         0.40               NaN        NaN      NaN
25        6            6.8         0.25               NaN        NaN      NaN
26        5            7.6         0.26               NaN        NaN      NaN
27        5            7.2         0.26               NaN        NaN      NaN
28        6            7.1         0.33               NaN        NaN      NaN
29        6            7.7         0.01               NaN        NaN      NaN
30        5            8.9         0.14               NaN        NaN      NaN
31        8            6.6         0.31              0.29      0.027     12.6
32        5            6.3         0.34               NaN        NaN      NaN
33        5            6.1         0.58               NaN        NaN      NaN
34        6            6.1         0.00               NaN        NaN      NaN
35        4            7.6         0.36               NaN        NaN      NaN

# <과제2>
- 구글링도 과제 수행에 포함되어 있습니다. 세션에 소개되지 않은 기능이 필요하다면, 구글링을 통해 구현해주시길 바랍니다.
- 데이터 : deliver.csv (날씨정보에 따른 배달품목별 주문량 데이터) / '내 드라이브'에 사본 저장할 것.

1. '날짜' 컬럼을 보고, '월' 컬럼과 '계절' 컬럼을 새로 추가하라.
(계절 컬럼 : 3-5월 : 봄, 6-8월 : 여름, 9-11월: 가을, 12-2월 : 겨울)

2. '미세먼지(㎍/㎥)' 컬럼에서 null값의 개수를 확인하고, null값을 전체 평균으로 대체하라.
(전체 평균은 null값이 아닌 값들의 평균으로 계산된다.)

In [32]:
deliver = pd.read_csv('/content/gdrive/MyDrive/ybigta/deliver.csv')
deliver.head()

,지역구,날짜,시간,습도,강수량,강수여부,기온,풍속,한식,분식,카페-디저트,일식,회,치킨,피자,양식,중식,"족발,보쌈",야식,"찜,탕",도시락,패스트푸드,미세먼지(㎍/㎥),요일,공휴일
0,강남구,2019-08-27,18,84,0.0,없음,24.6,1.2,0,0,0,0,0,0,0,0,0,5,0,0,0,0,28.0,화요일,0.0
1,강남구,2019-08-28,16,89,0.0,없음,24.1,1.9,0,0,0,0,0,0,0,0,0,1,0,0,0,0,32.0,수요일,0.0
2,강남구,2019-08-29,15,79,0.0,없음,22.1,0.9,0,0,0,0,0,0,0,0,0,2,0,0,0,0,30.0,목요일,0.0
3,강남구,2019-08-29,16,80,0.0,없음,21.7,0.8,0,0,0,0,0,0,0,0,0,5,0,0,0,0,30.0,목요일,0.0
4,강남구,2019-08-30,10,69,0.5,없음,23.6,3.6,0,0,0,0,0,0,0,0,0,5,0,0,0,0,20.0,금요일,0.0

In [33]:
deliver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68068 entries, 0 to 68067
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   지역구        68068 non-null  object
 1   날짜         68068 non-null  object
 2   시간         68068 non-null  int64
 3   습도         68068 non-null  int64
 4   강수량        68068 non-null  float64
 5   강수여부       68068 non-null  object
 6   기온         68068 non-null  float64
 7   풍속         68068 non-null  float64
 8   한식         68068 non-null  int64
 9   분식         68068 non-null  int64
 10  카페-디저트     68068 non-null  int64
 11  일식         68068 non-null  int64
 12  회          68068 non-null  int64
 13  치킨         68068 non-null  int64
 14  피자         68068 non-null  int64
 15  양식         68068 non-null  int64
 16  중식         68068 non-null  int64
 17  족발,보쌈      68068 non-null  int64
 18  야식         68068 non-null  int64
 19  찜,탕        68068 non-null  int64
 20  도시락        68068 non-null  int64
 21  패스트푸드      68068 non-null  int64
 22  미세먼지(㎍/㎥)  66732 non-null  float64
 23  요일         68068 non-null  object
 24  공휴일        68068 non-null  float64
dtypes: float64(5), int64(16), object(4)
memory usage: 13.0+ MB

In [37]:
import datetime as dt
deliver['날짜'] = pd.to_datetime(deliver['날짜'])

In [39]:
deliver['월'] = deliver['날짜'].dt.month
deliver.head()

,지역구,날짜,시간,습도,강수량,강수여부,기온,풍속,한식,분식,카페-디저트,일식,회,치킨,피자,양식,중식,"족발,보쌈",야식,"찜,탕",도시락,패스트푸드,미세먼지(㎍/㎥),요일,공휴일,월
0,강남구,2019-08-27,18,84,0.0,없음,24.6,1.2,0,0,0,0,0,0,0,0,0,5,0,0,0,0,28.0,화요일,0.0,8
1,강남구,2019-08-28,16,89,0.0,없음,24.1,1.9,0,0,0,0,0,0,0,0,0,1,0,0,0,0,32.0,수요일,0.0,8
2,강남구,2019-08-29,15,79,0.0,없음,22.1,0.9,0,0,0,0,0,0,0,0,0,2,0,0,0,0,30.0,목요일,0.0,8
3,강남구,2019-08-29,16,80,0.0,없음,21.7,0.8,0,0,0,0,0,0,0,0,0,5,0,0,0,0,30.0,목요일,0.0,8
4,강남구,2019-08-30,10,69,0.5,없음,23.6,3.6,0,0,0,0,0,0,0,0,0,5,0,0,0,0,20.0,금요일,0.0,8

In [40]:
def season(x) :
  if 3<=x<=5 :
    return '봄'
  elif  6<=x<=8 : 
    return '여름'
  elif 9<=x<=11 :
    return '가을'
  else :
    return '겨울'

In [43]:
deliver['계절'] = deliver['월'].apply(season)
deliver.head()

,지역구,날짜,시간,습도,강수량,강수여부,기온,풍속,한식,분식,카페-디저트,일식,회,치킨,피자,양식,중식,"족발,보쌈",야식,"찜,탕",도시락,패스트푸드,미세먼지(㎍/㎥),요일,공휴일,월,계절
0,강남구,2019-08-27,18,84,0.0,없음,24.6,1.2,0,0,0,0,0,0,0,0,0,5,0,0,0,0,28.0,화요일,0.0,8,여름
1,강남구,2019-08-28,16,89,0.0,없음,24.1,1.9,0,0,0,0,0,0,0,0,0,1,0,0,0,0,32.0,수요일,0.0,8,여름
2,강남구,2019-08-29,15,79,0.0,없음,22.1,0.9,0,0,0,0,0,0,0,0,0,2,0,0,0,0,30.0,목요일,0.0,8,여름
3,강남구,2019-08-29,16,80,0.0,없음,21.7,0.8,0,0,0,0,0,0,0,0,0,5,0,0,0,0,30.0,목요일,0.0,8,여름
4,강남구,2019-08-30,10,69,0.5,없음,23.6,3.6,0,0,0,0,0,0,0,0,0,5,0,0,0,0,20.0,금요일,0.0,8,여름

In [46]:
deliver[deliver['미세먼지(㎍/㎥)'].isnull()].head(20)

,지역구,날짜,시간,습도,강수량,강수여부,기온,풍속,한식,분식,카페-디저트,일식,회,치킨,피자,양식,중식,"족발,보쌈",야식,"찜,탕",도시락,패스트푸드,미세먼지(㎍/㎥),요일,공휴일,월,계절
8,강남구,2019-08-31,14,82,0.0,없음,23.2,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,토요일,0.0,8,여름
9,강남구,2019-09-02,8,46,0.0,없음,27.5,1.3,0,0,0,0,0,0,0,0,0,2,0,0,0,0,NaN,월요일,0.0,9,가을
10,강남구,2019-09-02,9,47,0.0,없음,27.1,0.5,0,0,0,0,0,0,0,0,0,10,0,0,0,0,NaN,월요일,0.0,9,가을
11,강남구,2019-09-02,10,49,0.0,없음,27.0,1.4,0,0,0,0,0,0,0,0,0,7,0,0,0,0,NaN,월요일,0.0,9,가을
12,강남구,2019-09-02,11,55,0.0,없음,26.6,1.3,0,0,0,0,0,0,0,0,0,7,0,0,0,0,NaN,월요일,0.0,9,가을
13,강남구,2019-09-02,13,66,0.0,없음,24.8,1.0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,NaN,월요일,0.0,9,가을
14,강남구,2019-09-02,15,78,0.0,없음,24.0,0.9,0,0,0,0,0,0,0,0,0,6,0,0,0,0,NaN,월요일,0.0,9,가을
15,강남구,2019-09-03,9,86,0.0,없음,23.4,3.2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,NaN,화요일,0.0,9,가을
16,강남구,2019-09-03,10,85,0.0,없음,23.5,1.9,0,0,0,0,0,0,0,0,0,5,0,0,0,0,NaN,화요일,0.0,9,가을
17,강남구,2019-09-03,11,86,0.0,없음,23.2,1.8,0,0,0,0,0,0,0,0,0,7,0,0,0,0,NaN,화요일,0.0,9,가을
18,강남구,2019-09-03,12,86,0.0,없음,23.1,1.4,0,0,0,0,0,0,0,0,0,7,0,0,0,0,NaN,화요일,0.0,9,가을
19,강남구,2019-09-03,13,85,0.0,없음,23.1,1.7,0,0,0,0,0,0,0,0,0,1,0,0,0,0,NaN,화요일,0.0,9,가을
20,강남구,2019-09-03,14,84,0.0,없음,23.1,2.4,0,0,0,0,0,0,0,0,0,5,0,0,0,0,NaN,화요일,0.0,9,가을
21,강남구,2019-09-05,10,94,0.0,없음,22.5,1.0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,NaN,목요일,0.0,9,가을
22,강남구,2019-09-05,11,96,0.0,없음,22.7,0.8,0,0,0,0,0,0,0,0,0,2,0,0,0,0,NaN,목요일,0.0,9,가을
4701,강서구,2019-12-13,0,43,0.0,없음,2.2,1.7,0,0,0,0,2,0,0,0,0,0,0,0,0,0,NaN,금요일,0.0,12,겨울
4702,강서구,2019-12-13,19,68,0.0,없음,2.9,2.2,2,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,금요일,0.0,12,겨울
4703,강서구,2019-12-13,21,76,0.0,없음,1.6,2.5,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,금요일,0.0,12,겨울
4704,강서구,2019-12-13,22,76,0.0,없음,1.4,1.7,0,0,1,0,1,0,0,0,0,0,0,0,0,0,NaN,금요일,0.0,12,겨울
4705,강서구,2019-12-13,23,68,0.0,없음,2.3,1.1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,금요일,0.0,12,겨울

In [49]:
deliver['미세먼지(㎍/㎥)'].fillna(deliver['미세먼지(㎍/㎥)'].mean(),inplace=True)
deliver.head(30)

,지역구,날짜,시간,습도,강수량,강수여부,기온,풍속,한식,분식,카페-디저트,일식,회,치킨,피자,양식,중식,"족발,보쌈",야식,"찜,탕",도시락,패스트푸드,미세먼지(㎍/㎥),요일,공휴일,월,계절
0,강남구,2019-08-27,18,84,0.0,없음,24.6,1.2,0,0,0,0,0,0,0,0,0,5,0,0,0,0,28.00000,화요일,0.0,8,여름
1,강남구,2019-08-28,16,89,0.0,없음,24.1,1.9,0,0,0,0,0,0,0,0,0,1,0,0,0,0,32.00000,수요일,0.0,8,여름
2,강남구,2019-08-29,15,79,0.0,없음,22.1,0.9,0,0,0,0,0,0,0,0,0,2,0,0,0,0,30.00000,목요일,0.0,8,여름
3,강남구,2019-08-29,16,80,0.0,없음,21.7,0.8,0,0,0,0,0,0,0,0,0,5,0,0,0,0,30.00000,목요일,0.0,8,여름
4,강남구,2019-08-30,10,69,0.5,없음,23.6,3.6,0,0,0,0,0,0,0,0,0,5,0,0,0,0,20.00000,금요일,0.0,8,여름
5,강남구,2019-08-30,11,72,0.0,없음,23.4,3.3,0,0,0,0,0,0,0,0,0,9,0,0,0,0,20.00000,금요일,0.0,8,여름
6,강남구,2019-08-30,12,72,0.0,없음,23.3,2.0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,20.00000,금요일,0.0,8,여름
7,강남구,2019-08-30,13,74,0.0,없음,23.0,2.5,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20.00000,금요일,0.0,8,여름
8,강남구,2019-08-31,14,82,0.0,없음,23.2,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,36.19349,토요일,0.0,8,여름
9,강남구,2019-09-02,8,46,0.0,없음,27.5,1.3,0,0,0,0,0,0,0,0,0,2,0,0,0,0,36.19349,월요일,0.0,9,가을
10,강남구,2019-09-02,9,47,0.0,없음,27.1,0.5,0,0,0,0,0,0,0,0,0,10,0,0,0,0,36.19349,월요일,0.0,9,가을
11,강남구,2019-09-02,10,49,0.0,없음,27.0,1.4,0,0,0,0,0,0,0,0,0,7,0,0,0,0,36.19349,월요일,0.0,9,가을
12,강남구,2019-09-02,11,55,0.0,없음,26.6,1.3,0,0,0,0,0,0,0,0,0,7,0,0,0,0,36.19349,월요일,0.0,9,가을
13,강남구,2019-09-02,13,66,0.0,없음,24.8,1.0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,36.19349,월요일,0.0,9,가을
14,강남구,2019-09-02,15,78,0.0,없음,24.0,0.9,0,0,0,0,0,0,0,0,0,6,0,0,0,0,36.19349,월요일,0.0,9,가을
15,강남구,2019-09-03,9,86,0.0,없음,23.4,3.2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36.19349,화요일,0.0,9,가을
16,강남구,2019-09-03,10,85,0.0,없음,23.5,1.9,0,0,0,0,0,0,0,0,0,5,0,0,0,0,36.19349,화요일,0.0,9,가을
17,강남구,2019-09-03,11,86,0.0,없음,23.2,1.8,0,0,0,0,0,0,0,0,0,7,0,0,0,0,36.19349,화요일,0.0,9,가을
18,강남구,2019-09-03,12,86,0.0,없음,23.1,1.4,0,0,0,0,0,0,0,0,0,7,0,0,0,0,36.19349,화요일,0.0,9,가을
19,강남구,2019-09-03,13,85,0.0,없음,23.1,1.7,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36.19349,화요일,0.0,9,가을
20,강남구,2019-09-03,14,84,0.0,없음,23.1,2.4,0,0,0,0,0,0,0,0,0,5,0,0,0,0,36.19349,화요일,0.0,9,가을
21,강남구,2019-09-05,10,94,0.0,없음,22.5,1.0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,36.19349,목요일,0.0,9,가을
22,강남구,2019-09-05,11,96,0.0,없음,22.7,0.8,0,0,0,0,0,0,0,0,0,2,0,0,0,0,36.19349,목요일,0.0,9,가을
23,강남구,2019-09-23,9,57,0.0,없음,21.7,1.7,0,0,0,0,0,0,0,0,0,2,0,0,0,0,13.00000,월요일,0.0,9,가을
24,강남구,2019-09-23,10,59,0.0,없음,21.0,2.1,0,0,0,0,0,0,0,0,0,3,0,0,0,0,13.00000,월요일,0.0,9,가을
25,강남구,2019-09-23,11,62,0.0,없음,20.2,1.1,0,0,0,0,0,0,0,0,0,4,0,0,0,0,13.00000,월요일,0.0,9,가을
26,강남구,2019-09-23,12,59,0.0,없음,20.2,0.9,0,0,0,0,0,0,0,0,0,3,0,0,0,0,13.00000,월요일,0.0,9,가을
27,강남구,2019-09-24,16,84,0.0,없음,17.8,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,25.00000,화요일,0.0,9,가을
28,강남구,2019-09-26,8,51,0.0,없음,25.7,0.7,0,0,0,0,0,0,0,0,0,0,0,1,0,0,28.00000,목요일,0.0,9,가을
29,강남구,2019-09-26,9,56,0.0,없음,24.9,1.3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,28.00000,목요일,0.0,9,가을